// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Event struct {
	ID          int64
	Name        string
	Description string
	Location    string
	Datetime    time.Time
	UserID      sql.NullInt64
}

type Registration struct {
	ID      int64
	EventID int64
	UserID  int64
	Foreign interface{}
}

type User struct {
	ID       int64
	Email    string
	Password string
}
