// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Event struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Location    string    `json:"location"`
	Datetime    time.Time `json:"datetime"`
	UserID      int64     `json:"userId"`
}

type Registration struct {
	ID      int64       `json:"id"`
	EventID int64       `json:"eventId"`
	UserID  int64       `json:"userId"`
	Foreign interface{} `json:"foreign"`
}

type User struct {
	ID       int64  `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
