// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    name, description, location, dateTime, user_id
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, name, description, location, datetime, user_id
`

type CreateEventParams struct {
	Name        string
	Description string
	Location    string
	Datetime    time.Time
	UserID      sql.NullInt64
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Name,
		arg.Description,
		arg.Location,
		arg.Datetime,
		arg.UserID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.Datetime,
		&i.UserID,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = ?
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const deleteRegistration = `-- name: DeleteRegistration :exec
DELETE FROM registrations 
WHERE event_id = ? AND user_id = ?
`

type DeleteRegistrationParams struct {
	EventID int64
	UserID  int64
}

func (q *Queries) DeleteRegistration(ctx context.Context, arg DeleteRegistrationParams) error {
	_, err := q.db.ExecContext(ctx, deleteRegistration, arg.EventID, arg.UserID)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, name, description, location, datetime, user_id FROM events
WHERE id = ?
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.Datetime,
		&i.UserID,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, name, description, location, datetime, user_id FROM events
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Location,
			&i.Datetime,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerEventUser = `-- name: RegisterEventUser :one
INSERT INTO registrations (
    event_id, user_id
) VALUES (
    ?, ?
)
RETURNING id, event_id, user_id, "foreign"
`

type RegisterEventUserParams struct {
	EventID int64
	UserID  int64
}

func (q *Queries) RegisterEventUser(ctx context.Context, arg RegisterEventUserParams) (Registration, error) {
	row := q.db.QueryRowContext(ctx, registerEventUser, arg.EventID, arg.UserID)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Foreign,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET name = ?, description = ?, location = ?, dateTime = ?
WHERE id = ?
RETURNING id, name, description, location, datetime, user_id
`

type UpdateEventParams struct {
	Name        string
	Description string
	Location    string
	Datetime    time.Time
	ID          int64
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.Name,
		arg.Description,
		arg.Location,
		arg.Datetime,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.Datetime,
		&i.UserID,
	)
	return i, err
}
